[build]
  base = "docs"
  publish = "dist"
  command = "pnpm build"

[context.production]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
  
[context.deploy-preview]
  # Skip preview deploy if no changes in docs/
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."