name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.platform }} (electron-forge)
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macOS
            make-cmd: pnpm make:macos
            artifact-name: Atlassify-dist-mac
          - os: windows-latest
            platform: Windows
            make-cmd: pnpm make:win
            artifact-name: Atlassify-dist-win
          - os: ubuntu-latest
            platform: Linux
            make-cmd: pnpm make:linux
            artifact-name: Atlassify-dist-linux
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Make application for ${{ matrix.platform }}
        run: ${{ matrix.make-cmd }}
        env:
          APTABASE_KEY: ${{ secrets.APTABASE_KEY }}
          APPLE_ID: ${{ secrets.APPLE_ID_USERNAME }}
          APPLE_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD  }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_ID_TEAM_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ matrix.artifact-name }}
          path: out/make/**/*
          overwrite: true
